# Generated by Django 5.1.3 on 2024-11-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('image', models.ImageField(upload_to='disease_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('farmer_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('contact_info', models.CharField(max_length=255)),
                ('farmer_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resource_id', models.AutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=255)),
                ('reported_cases', models.IntegerField()),
                ('date_reported', models.DateField()),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goathubapp.disease')),
            ],
        ),
        migrations.CreateModel(
            name='VeterinaryConsultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_id', models.IntegerField()),
                ('date_requested', models.DateField()),
                ('disease_reported', models.TextField()),
                ('veterinary_response', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='goathubapp.disease')),
            ],
        ),
    ]
