# Generated by Django 5.1.3 on 2024-12-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goathubapp', '0002_farmerregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerregistration',
            name='farmer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='goathubapp.farmer'),
        ),
    ]
