# Generated by Django 5.1.3 on 2024-12-05 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goathubapp', '0003_farmerregistration_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationReply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_message', models.TextField()),
                ('reply_image', models.ImageField(blank=True, null=True, upload_to='replies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCase',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='special_cases/')),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VetConsultation',
            fields=[
                ('consultation_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('veterinary_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='statistics',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='veterinaryconsultation',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='veterinaryconsultation',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmerregistration',
            name='farmer',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.AddField(
            model_name='consultationreply',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='goathubapp.vetconsultation'),
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='VeterinaryConsultation',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
